# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('age', models.IntegerField()),
                ('email_address', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender/Sex')),
                ('course', models.CharField(choices=[('web-dev', 'Web Development'), ('pub-hlth', 'Public Health'), ('data-lst', 'Data Analyst')], max_length=10, verbose_name='Course Title')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_title', models.CharField(max_length=250, verbose_name='Task Title')),
                ('task_given', models.TextField(verbose_name='Task Given')),
                ('task_startdate', models.DateField()),
                ('task_deadline', models.DateField()),
                ('comment', models.TextField(max_length=500, verbose_name='Comment')),
            ],
        ),
    ]
