# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('web-dev', 'Web Development'), ('pub-hlth', 'Public Health'), ('data-lst', 'Data Analysis')], max_length=10, verbose_name='Course Title'),
        ),
    ]
